# Generated by Django 5.2.8 on 2026-04-01 00:00 tanlianwang

import uuid_utils.compat
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0005_usermenusetting'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlPolicy',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='策略描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('access_time_enabled', models.BooleanField(default=False, verbose_name='是否限制访问时段')),
                ('access_start_time', models.TimeField(blank=True, null=True, verbose_name='访问开始时间')),
                ('access_end_time', models.TimeField(blank=True, null=True, verbose_name='访问结束时间')),
                ('allowed_weekdays', models.JSONField(default=list, verbose_name='允许访问星期')),
                ('allowed_device_types', models.JSONField(default=list, verbose_name='允许接入设备类型')),
                ('allowed_regions', models.JSONField(default=list, verbose_name='允许接入区域')),
                ('effect_start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效开始时间')),
                ('effect_end_time', models.DateTimeField(blank=True, null=True, verbose_name='生效结束时间')),
                ('application_count', models.PositiveIntegerField(default=0, verbose_name='应用次数')),
                ('last_applied_time', models.DateTimeField(blank=True, null=True, verbose_name='最近应用时间')),
            ],
            options={
                'db_table': 'access_control_policy',
                'ordering': ['-update_time', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AccessControlPolicyApplicationRecord',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('policy_name', models.CharField(max_length=128, verbose_name='策略名称快照')),
                ('target_type', models.CharField(choices=[('DEVICE', '设备'), ('SERVICE', '服务')], max_length=32, verbose_name='应用对象类型')),
                ('target_name', models.CharField(max_length=128, verbose_name='应用对象名称')),
                ('target_identifier', models.CharField(blank=True, default='', max_length=128, verbose_name='应用对象标识')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('operator_name', models.CharField(blank=True, default='', max_length=128, verbose_name='操作人名称')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='操作人')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_records', to='system_manage.accesscontrolpolicy', verbose_name='策略')),
            ],
            options={
                'db_table': 'access_control_policy_application_record',
                'ordering': ['-create_time'],
            },
        ),
    ]
